### ISSUE TITLE
Tensorflow 1.7 docker image

### ISSUE THREAD

**Issue by PedroCardoso** [aws/sagemaker-tensorflow-containers#40]
Any reason why the Tensorflow 1.7 branch is not merged ?
It would be very useful to use Tensorflow HUB

**Comment by winstonaws** [comment]
Thanks for the interest - we're actively working on decreasing the time from framework version release to inclusion in our containers.  We haven't merged it yet to ensure we have sufficient time to appropriately test, but you're free to use this branch to experiment.  

Also, even after 1.7 is released, you'll need to pip install tensorflow-hub yourself to use that functionality.

**Comment by laurenyu** [comment]
closing as the TF 1.7 image has now been released
