### ISSUE TITLE
When I want to download the docker image from ec2 container repository, login validation fails

### ISSUE THREAD

**Issue by giggle0312** [aws/sagemaker-tensorflow-containers#42]
1. The docker image named "382416733822.dkr.ecr.us-east-1.amazonaws.com/linear-learner:latest" was produced after traning linear-learner model.
2. We have applied a EC2 instance and deployed a docker node.
3. Excute the login validation commend: `aws ecr get-login --registry-ids 382416733822` and get the response as follows:
`docker login -u AWS -p eyJwYXlsb2FkIjoieXRqcUpOZ0FKUWV0RnExTks2ZWhCVHQ3MytYVit0eUxwY2swZmFuM055Y0llczVBNGc0L29HMFhEYWhsQSt6ZDNtZWFWQjJpcXY4dEt5dERmM3c0c1VQYnJVamFScitCeGUxRlJ5b2dLNlhYWHlMOXQ3WFJmRHNtSjMyUmtONUJOdERqTm45SEJjV1J3OG9hZy9ISUpNeDFhRWg2U1k1OWY1SkZLdEZtTE9OZVgzVm1QaXViR3hSdlVxdGlQc0hkay95SG1CaEdjQ3JwR01tQnZLNElVQ1lrUldpS3pDcTNLc0xNbU1SRGlnS3ZuVWUyemlZQmE0L0VRY2lZTGtDekI2UGZNZ2tCNjNSdVV2U3BObDBYVHFjV3NhY09heXV1b1E4d0ZtbGZRZUZSc2FNMTdPdlZrTTBZZHNrVTVRS2ZDTHVmWnlhUU1tUlFvRG00bllsdFJpWGZYaXZyMDBtNGlHYlkwZ0NQY3FvcE1uNC8zOERUWk92RnhDeTFQK1hBV25YVUxGa29uUVNsdHJVSXJyUXBrdmtXdEltWFQ0ck5xNEtKSks1cW5TdURsUnFrWXZlQWZoamhFSHJsMWxIQ2NvR2tjUzBxTkJVdnQvbG1hQmxBdFQrWW1wU3BxWGJhSUI4WmExSmZTRzRPNmp0SEZLMWNOcnBTWUwvcDVZY0pCSWxPVjY2NnBmTjNvSnEyVU1WZ2tubWZMcVVyTk5VcnZNNjI1MWIxdlgrTW1LS09keW4yQ0xIOVpRSitNazhPb2dzcVUraFpsdzRZeTZiMjhsRCs4bkxTb2pvVjFSN01rckVNN2Vxbk1SRm5nUi9QelBTYkx0dkQ5WGVyRHVHdk1HZm1KR2JVRmFIM2ZtMWJXYzZMZ0cvTXl3RnBLMFZwV0Vnd0ZrWGZEblhlS1YzSk11aU5BUnFOS0toL05GVGEva2dHWGx1dERCR0JFY2RjYkJvWG5RSXRIWDQ4dStzSXhCb1h0TnJ0Q3RWVk16ZkI3YzNVcFVRMnBkcnFESHBmNmt2cmU4MkJBOWZaQVN6MUhia21Za0lKL1hXMUZGcDBiTjQrVGIxelg1ZzRtNmNqeldEVllTeWZWT05QK04xbGtBMGk3ekpoeEQxV1ljTkxycWM2Uzc4elRsRHAwaUJRZlNqNm8xTE9CVkk4SXovZXZnMk5JR3VVWkx6dDJxS3Y2MTNBQlE4R3RXd1JuQWhsY0U5cVp0azdDTjVXTjljY0RNZ0h3ckY4V0c5L1lzbmY4VVJZTGVHM1V0MkpwSGRRdTgvWGJZNGoxRkhZRnArOFZTZ0NVZ3FNVk5KdVpGQVNLQWk0NDZtNUw0MmZNaHpSUVNOSnc0Wlozd08rTDBUaDFncmNab0hoUlN5aTRKNTBqVnZuUWNZeTB0d0wvVDFsK2hLTzkyWEt4QkZWSWpZYjAzWnN0MTh2S3ZDcnNjQ0ZWekk9IiwiZGF0YWtleSI6IkFRRUJBSGh3bTBZYUlTSmVSdEptNW4xRzZ1cWVla1h1b1hYUGU1VUZjZTlScTgvMTR3QUFBSDR3ZkFZSktvWklodmNOQVFjR29HOHdiUUlCQURCb0Jna3Foa2lHOXcwQkJ3RXdIZ1lKWUlaSUFXVURCQUV1TUJFRURMdjZ2VFZhVjF3bGVORjdvZ0lCRUlBN0k4eElHaVdlNGxoNnFDU2tkQVRPVWo5UEZ6UkExN3dkOGNWKzBOUUVKdkxXdHJmSDFnM0J1bWdZMi9tVlBrbkJQbkhOTW1GemhXZzZkb3M9IiwidmVyc2lvbiI6IjIiLCJ0eXBlIjoiREFUQV9LRVkiLCJleHBpcmF0aW9uIjoxNTI3NzE0OTUzfQ== **-e none** https://382416733822.dkr.ecr.us-east-1.amazonaws.com`
4.Then I copy above validation on EC2, it returns a error `unknown shorthand flag: 'e' in –e`. So I delete the `-e none` manually and excute the validation https again, it retures `WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded`
It looks like I have login-ed in successfully. 
5. However, when I try to pull the docker image from ec2 container executing commend `docker pull 382416733822.dkr.ecr.us-east-1.amazonaws.com/linear-learner:latest` . It returns a error information that `Error response from daemon: pull access denied for 382416733822.dkr.ecr.us-east-1.amazonaws.com/linear-learner, repository does not exist or may require 'docker login`
So I don't know the reason that I failed to pull the image from ec2 repository.

**Comment by winstonaws** [comment]
Hey, thanks for your interest!

"382416733822.dkr.ecr.us-east-1.amazonaws.com/linear-learner:latest" is an official sagemaker algorithm image, which runs a proprietary algorithm developed by the SageMaker team. They aren't available for pulling from ECR for this reason - to protect the intellectual property.

**Comment by elgalu** [comment]
Hi! does this also apply to DeepAR? I'm also getting:

```
Error response from daemon: repository 962522375529.dkr.ecr.us-east-1.amazonaws.com/forecasting-deepar not found
```
