### ISSUE TITLE
How to put model for training in the container?

### ISSUE THREAD

**Issue by nekojan** [aws/sagemaker-tensorflow-containers#43]
I'm confused. I followed the instruction but it isn't clear at all.

Now I have built the image and when I run it (`docker run -it tensorflow-base:1.7.0-cpu-py2`), I get a docker container with 
> tensorflow-model-server_1.7.0_all.deb

If I have a model for training (.py or .ipynb file), how do I put it in the container so I can train this model on SageMaker? (Training data is on S3).

**Comment by winstonaws** [comment]
Hi @nekojan,

The easiest way to use the SageMaker Tensorflow image to train on SageMaker is to use the SageMaker Python SDK. See: https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst

Specifically, this part: https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst#tensorflow-sagemaker-estimators

There's more example code here as well: https://github.com/awslabs/amazon-sagemaker-examples/tree/master/sagemaker-python-sdk

The instructions on this repository are focused on how to build the official SageMaker docker images. However, for normal use, you don't need to do this as we publish official versions that are publically available for use. Mostly, this would be useful if you want to change the code or dependencies in the image.

**Comment by nekojan** [comment]
Hello @winstonaws  Thank you for the answer.
Our team uses Python 3 and Tensorflow 1.8 to create models. From what I understand, the SDK doesn't support Python 3 yet, and the only way to train our current models on SageMaker is to create our own Docker image, would that be correct?

**Comment by yangaws** [comment]
Hi @nekojan ,

Yes you are correct. Now our container supports neither python 3 nor TensorFlow 1.8. You may need to write your own container for now.

I will mark this as a feature request.

Thanks

**Comment by nekojan** [comment]
@yangaws Thank you!
I'm trying out what's available on this repository for now (python 2 with TF 1.6 and 1.7), I'm still confused on how to get the model for training inside the container.

**Comment by yangaws** [comment]
Hi @nekojan ,

As @winstonaws answered, the easiest way is to use SageMaker Python SDK. We have already built our production image for training and prediction. What you could do with SageMaker Python SDK is to prepare the data and the training/prediction script and invoke our production image to train/predict.

You could check out the links @winstonaws provides. It includes a repo with a bunch of example notebooks for using SageMaker Python SDK with our production tensorflow container. And the readme has instructions for how to write your .py file that runs training in the container.

**Comment by nekojan** [comment]
Ok. I'm closing this. Thank you.
