### ISSUE TITLE
Can I use Python 3?

### ISSUE THREAD

**Issue by nekojan** [aws/sagemaker-tensorflow-containers#44]
Since the model is in container, I'm assuming that I should be able to use Python 3. 
But if I can't, could you please explain why? Thank you.

**Comment by winstonaws** [comment]
At this moment, we don't support python 3 with our official image, but we are planning to. There's a lot on our plate at the moment, but this is one of the things we know is important to add.

In the meantime, if you absolutely need to use python 3, you can build your own image by following the instructions in this repository, with small modifications to the dockerfiles.

**Comment by nekojan** [comment]
Thank you! I've tried following the instruction for building image, but I'm stuck since I'm new to Docker. Please see issue #43
